services:
  ai-pm-cache:
    image: redis:7.2-alpine
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ai_pm_cache_vol:/data
    container_name: ai-tools-pm-cache

  ai-pm-database:
    image: postgres:15
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AI_PM_DB_USER:-aipm}
      POSTGRES_PASSWORD: ${AI_PM_DB_PASSWORD:-aipm123}
      POSTGRES_DB: ${AI_PM_DB_NAME:-ai_project_manager}
    volumes:
      - ai_pm_db_vol:/var/lib/postgresql/data
    container_name: ai-tools-pm-database
    ports:
      - "5432:5432"

  ai-pm-storage:
    image: minio/minio
    platform: linux/amd64
    restart: unless-stopped
    command: server /export --console-address ":9090"
    environment:
      MINIO_ROOT_USER: ${AI_PM_STORAGE_USER:-aipm}
      MINIO_ROOT_PASSWORD: ${AI_PM_STORAGE_PASSWORD:-aipm123}
    volumes:
      - ai_pm_storage_vol:/export
    container_name: ai-tools-pm-storage
    ports:
      - "9000:9000"
      - "9090:9090"

  ai-pm-api:
    build:
      context: ./pm-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AI_PM_DB_HOST: ai-pm-database
      AI_PM_DB_PORT: "5432"
      AI_PM_DB_USER: ${AI_PM_DB_USER:-aipm}
      AI_PM_DB_PASSWORD: ${AI_PM_DB_PASSWORD:-aipm123}
      AI_PM_DB_NAME: ${AI_PM_DB_NAME:-ai_project_manager}
      PORT: "8000"
    ports:
      - "8000:8000"
    depends_on:
      - ai-pm-database
      - ai-pm-cache
      - ai-pm-storage
    container_name: ai-tools-pm-api

  ai-pm-ui:
    build:
      context: ./pm-ui
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "3001:80"
    depends_on:
      - ai-pm-api
    container_name: ai-tools-pm-ui

volumes:
  ai_pm_cache_vol:
  ai_pm_db_vol:
  ai_pm_storage_vol:
