// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConfiguration(arg1) {
  return window['go']['wails']['App']['CreateConfiguration'](arg1);
}

export function GetAvailableTools() {
  return window['go']['wails']['App']['GetAvailableTools']();
}

export function GetRecommendedPorts(arg1) {
  return window['go']['wails']['App']['GetRecommendedPorts'](arg1);
}

export function GetSystemInfo() {
  return window['go']['wails']['App']['GetSystemInfo']();
}

export function GetToolDefaultConfig(arg1) {
  return window['go']['wails']['App']['GetToolDefaultConfig'](arg1);
}

export function IsPortAvailable(arg1) {
  return window['go']['wails']['App']['IsPortAvailable'](arg1);
}

export function LaunchTool(arg1) {
  return window['go']['wails']['App']['LaunchTool'](arg1);
}

export function ListInstances() {
  return window['go']['wails']['App']['ListInstances']();
}

export function StopTool(arg1) {
  return window['go']['wails']['App']['StopTool'](arg1);
}

export function ValidateConfiguration(arg1) {
  return window['go']['wails']['App']['ValidateConfiguration'](arg1);
}
