// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecases} from '../models';
import {entities} from '../models';
import {services} from '../models';

export function CreateConfiguration(arg1:usecases.CreateConfigRequest):Promise<entities.Configuration>;

export function GetAvailableTools():Promise<Array<string>>;

export function GetRecommendedPorts(arg1:string):Promise<Record<string, number>>;

export function GetSystemInfo():Promise<services.SystemInfo>;

export function GetToolDefaultConfig(arg1:string):Promise<Record<string, any>>;

export function IsPortAvailable(arg1:number):Promise<boolean>;

export function LaunchTool(arg1:string):Promise<entities.AIToolInstance>;

export function ListInstances():Promise<Array<entities.AIToolInstance>>;

export function StopTool(arg1:string):Promise<void>;

export function ValidateConfiguration(arg1:usecases.CreateConfigRequest):Promise<void>;
